<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Riparian soil nitrogen cycling and isotopic enrichment in response to a long-term salmon carcass manipulation experiment
1.1 ABSTRACT

  Pacific salmon acquire most of their biomass in the ocean before returning to spawn and die in coastal streams and lakes, thus providing subsidies of marine-derived nitrogen (MDN) to freshwater and terrestrial ecosystems. Recent declines in salmon abundance have raised questions of whether managers should mitigate for losses of salmon MDN subsidies. To test the long-term importance of salmon subsidies to riparian ecosystems we measured soil N cycling in response to a 20-year manipulation where salmon carcasses were systematically removed from one bank and deposited on the opposite bank along a 2 km stream in southwestern Alaska. Soil samples were taken at different distances from the stream bank along nine paired transects and measured for organic and inorganic nitrogen concentrations, and nitrogen transformation rates. MDN was measured using ^15^N/^14^N for bulk soils, and NH~4~^+^ and NO~3~^-^ soil pools. Stable isotope analyses confirmed ^15^N/^14^N was elevated on the salmon enhanced bank compared to the salmon depleted bank. However, ^15^N/^14^N values of plant-available inorganic nitrogen exceeded the ^15^N/^14^N of salmon inputs, highlighting N isotope fractionation in soils that raises significant methodological issues with standard MDN assessments in riparian systems. Surprisingly, despite 20 years of salmon supplementation, the presence of MDN did not cause a long-term increase in soil N availability. This finding indicates the importance of MDN to ecosystem N biogeochemistry and riparian vegetation may be overestimated for some systems. Given that essential nutrients can also be pollutants, we urge more critical analyses of the role of MDN to inform compensatory mitigation programs targeting salmon nutrient enhancement.

1.2 INTRODUCTION
  
  Pacific salmon (*Oncorhynchus spp.*) migration from marine environments to freshwater spawning grounds is a textbook case of cross-ecosystem nutrient subsidies, and dozens of studies have identified the presence of marine-derived nitrogen (MDN) from salmon as crossing ecosystem boundaries from oceans to freshwaters and into the terrestrial environment (sensu, [@Polis2004; @Gende2002; @Schindler2003]. Declines in Pacific salmon populations in many areas, caused by human activities (overharvest, habitat degradation, dams) [@Gustafson2007], and the concern over loss of MDN to coastal watersheds has made restoration of salmon nutrients a focal point for many management and mitigation strategies. For example, in the Columbia River Basin where Pacific salmon populations have declined, legislation requiring compensatory mitigation has led to nutrient enhancement programs, on the foundation that habitats have lost critical nutrients from salmon and therefore augmentation is necessary to maintain ecosystem function [@Collins2015]. 

  Salmon bring nutrients, including phosphorus (P) and other compounds in addition to nitrogen (N), into freshwater and terrestrial food webs through two pathways: 1) direct consumption of tissues by predators and scavengers, and 2) autotrophic or heterotrophic assimilation of nutrients released as salmon spawn, die, and eventually decay [@Gende2002]. Salmon are enriched in the heavy isotope of nitrogen (^15^N) relative to the light isotope (^14^N) when compared to terrestrial and watershed-derived N. This isotopic enrichment has been used to quantitatively trace the presence of salmon derived nutrients into watersheds [@Schindler2003]. For example, the proportion of N derived from salmon ranges from approximately 30% – 75% in fish and aquatic invertebrates [@Naiman2002], 10 – 90% in piscivorous mammals such as bears, and 20 – 40% in piscivorous fishes near salmon spawning grounds [@Bilby1996; @Hilderbrand1999; @Chaloner2002; @Claeson2006].
  
  The annual return of this predictable and abundant, yet temporally limited, high quality resource drives the foraging ecology of both terrestrial and aquatic consumers [@Quinn2018; @Schindler2013]. Carcasses and roe are documented food sources for over 22 species of mammals, birds [@Cenderholm1989], fishes [@Scheuerell2007], and invertebrates [@Minakawa2002; @Meehan2005; @Winder2005]. Bear population density, body size, and reproductive output has been correlated with meat (primarily salmon) consumption, with piscivorous populations having 55 times higher density than their meat-limited counterparts [@Hilderbrand1999]. In aquatic ecosystems, salmon carcass abundance has been correlated with elevated growth rates of invertebrates, and with size, density, and condition factor of juvenile salmonids [@Bilby1998; @Minakawa2002; @Wipfli2003]. 

The presence of MDN has been documented in aquatic primary producers, though its overall ecological importance remains ambiguous. Via this bottom-up pathway, salmon supply critical limiting nutrients that can increase primary and/or bacterial productivity, which are subsequently transferred to consumers and up through the food web [@Wipfli1998; @Chaloner2002; @Holtgrieve2011]. Higher salmon returns are correlated with MDN signatures in lower trophic levels including zooplankton and periphyton [@Kline1993; @Finney2000; @Holtgrieve2010]. Both direct ecological and paleolimnological evidence suggest MDN and P positively influence primary production in lakes [@Moore2007]. For example, commercial fisheries remove upwards of two-thirds of MDN which would otherwise enter some freshwater lakes in Alaska, resulting in a 3-fold decline in algal production [@Schindler2005]. In stream ecosystems, the decomposition of salmon increases dissolved organic and inorganic nutrients, including highly available forms such as orthophosphate (PO~4~^3-^) and ammonia/ammonium (NH~3~/NH~4~^+^). These nutrients can stimulate epilithon growth (bacteria and algae), though the magnitude of this response is highly variable, and dependent on other growth limiting factors such as sunlight and disturbance [@Johnston2004; @Mitchell2005; @Janetski2009].
	
  In the terrestrial realm, bottom-up effects of MDN from salmon are also thought to be ecologically important, though this has been difficult to demonstrate rigorously. Studies across the range of salmon in North America have inferred that up to 26% of foliar N in riparian plants is marine derived, with foliar N levels often correlating with salmon abundance and distance from the salmon spawning location [e.g., @Hocking2012; @Reimchen2013]. While MDN is clearly present in terrestrial producers, direct evidence of the importance of MDN for ecosystem function and productivity is much less evident. @Helfield2001 measured tree growth increments in areas with and without salmon and found higher growth in one species (Sitka spruce) in areas where salmon nutrients were present, although these findings were later contested on statistical grounds [@Kirchoff2003]. @Hocking2012 observed decreased understory plant diversity with increasing salmon abundance, though this pattern was largely attributed to increased dominance of a single N tolerant species (salmonberry). @Reimchen2013 suggested that salmon abundance increased tree growth, but tree ring ^15^N/^14^N values were not related to salmon abundance; other growth limiting factors such as temperature and location were important covariates. Most recently, @Quinn2018 examined tree growth increments in the riparian zone of a small Alaskan stream before and after a 20-year, > 200,000 kg, salmon carcass manipulation. In the two decades prior to manipulation, white spruce (*Picea glauca*) on average grew faster on one bank compared to the other. The subsequent decades of carcass manipulation enriched the naturally slower growing side, and were associated with increased growth. However, the growth effect of the carcasses was smaller than the natural side-to-side variation, and other important site and landscape factors such as forest demography, climate, aspect, and water availability were not fully considered, a common trend in MDN studies of riparian vegetation.
  
  Interpreting the contributions of MDN to terrestrial producers using stable isotopes is often highly simplified, and does not consider how variability of N sources and overall N availability may confound results. MDN analyses apply simple two-source mixing models to infer the proportion of total N derived from salmon. When applied to terrestrial vegetation, the terrestrial end-member for the mixing models is typically determined by sampling the ^15^N/^14^N of the same species of plant either laterally away from the stream (where MDN contribution is expected to be small), upstream of barriers to salmon migration, or in watersheds without salmon. For the salmon end-member, a single value equal to the average ^15^N/^14^N of salmon (12.62 ± 0.31 per mille for sockeye salmon) is typically used (S1). Inherent assumptions with these models therefore include: 1) reference sites are biogeochemically similar to salmon sites and 2) the isotopic signature of salmon is unchanged in the soils prior to plant uptake. N cycling in soils is strongly controlled by position in the landscape and contains a number of chemical reactions which fractionate N isotopically [@Hogberg1997; @Wheeler2014; Figure 1], therefore these assumptions may not be valid.  
  
Experiments examining the contributions of MDN are often limited by short timescales, and relatively few experiments investigate changes in plant-available soil N pools important to plant nutrient uptake and growth [@Collins2015]. Studies examining spatial and temporal impacts of salmon on soil inorganic N have identified highly localized responses (effects only observed < 30 cm from carcasses) where soil ammonium (NH~4~^+^) and nitrate (NO~3~^-^) increase for weeks to months [@Drake2005; @Gende2007; @Holtgrieve2009] and rarely consider long-term N retention in the system. Experiments typically examine the contributions of MDN by nutrient addition not nutrient removal; however, nutrient removal is important for understanding the effects of lower numbers of salmon returning to coastal watersheds due to fishing, habitat reduction, and climate change. In addition, previous research observed a strong effect of watershed slope on ^15^N/^14^N in riparian plants and attributed this to topography concentrating carcasses near streams [@Hockings2012]. However, watershed topography also influences soil water content and N cycling, which affect N isotopes [@Hogberg1997] and therefore complicates MDN assessments. 
	
To resolve the extent to which salmon carcasses contributed MDN to plant-available N pools and the long-term ecological response to this subsidy, we present a second study of the 20-year carcass manipulation experiment described in @Quinn2018. While @Quinn2018 focused on tree growth before and after the manipulation, the objective of this work was to determine whether prolonged enhancement and reduction of salmon subsidies altered long-term soil N cycling, similar to that documented in forests receiving N fertilizer additions [@Prescott1992; @Prescott1995; @Lu2010]. If long-term changes in N availability due to salmon enhancement or reduction were observed, compensatory nutrient subsidies may be valuable for maintaining critical ecosystem functions in riparian areas with reduced salmon returns. If not, then the addition of nutrients as a management response to low salmon returns may have unintended negative consequences [sensu @Compton2006]. Specifically, the importance of MDN to riparian ecosystems was assessed by 1) evaluating the presence of MDN in soils enhanced and depleted in salmon carcasses through bulk stable isotope analysis of N, 2) quantifying the response of plant-available N pools ([NH~4^+^] and [NO~3^-^]) and their rate of supply via mineralization and nitrification, 3) considering how fractionation in soils may impact mixing model results by measuring ^15^N/^14^N of NH~4^+^ and 4) comparing these results to the vegetation responses measured by @Quinn2018 at the same site. This research fills key knowledge gaps by examining the long-term legacy of inorganic N pools, both salmon addition and removal, and considering site variability that may impact the assumption of biogeochemical similarity between test and control sites, following a 20-year manipulation.

 

