# Conclusion {-}

While extensive research has explored how ocean acidification can act as a selective force upon less tolerant phenotypes and associated genotypes from a population and allow resilient ones to proliferate [@Logan2021; @Bitter2019; @Sunday2014; @Sunday2011], this framework may not account for sublethal or nonlethal impacts that are not easily documented. Without understanding these impacts, we are unable to connect observed phenotypes with physiological mechanisms defining environmental responses. My dissertation uses the Pacific oyster, *Crassostrea gigas*, as a model organism to demonstrate how proteomic and epigenetic analysis can elucidate sub- and nonlethal impacts of ocean acidification on marine invertebrates. My findings can be used to expand the conceptual model used to interpret low pH impacts on physiology. 

Importantly, my dissertation helps elucidate the functional role of environmentally-responsive DNA methylation. Concentration of methylation in genes suggests a role in regulating gene expression. Methylation may reduce transcriptional noise so C. gigas can be more efficient when maintaining homeostasis under stressful conditions [@Roberts2012]. My finding that somatic and reproductive have distinct responses to low pH stress is characteristic of these tissues having different roles within an organism. To maintain tissue function, different processes would need to be targeted via changes in gene methylation. 

Methylation control of transcriptional processes could allow organisms to acclimate to ocean acidification, changing the outcome of selection. If the environment remains stable and offspring inherit these methylation patterns, then selection outcomes would again be altered. However, organisms may require spurious transcription if the environment is unpredictable or variable, such as temporary low pH events associated with seasonal upwelling. In this case, methylation regulation of transcription would not provide resilience and could lead to poorer survival. Even if less-tolerant genotypes are unable to deregulate transcriptional processes in a fluctuating environment, resource competition with tolerant genotypes while alive could impact fitness of those tolerant genotypes. Therefore, it is critical to consider methylation when considering the ramifications of ocean acidification not only at an organismal level, but at an ecological level. With my dissertation as a foundation, future work can explore the role of DNA methylation in modulating carryover effects to environmental stressors, and determine how methylation can interact with gene expression, protein abundance, or other epigenomic mechanisms to shape physiological phenotype and ecological interactions.