---
# UW thesis fields
title: "Molecular techniques for resilient Pacific oyster (*Crassostrea gigas*) aquaculture"
author: "Yaamini R. Venkataraman"
year: "2021"
program: "School of Aquatic and Fishery Sciences"
chair: "Steven B. Roberts"
chairtitle: "Associate Professor"
signature1: "Jacqueline Padilla-Gamiño"
signature2: "Jonathan P. Davis"
abstract: |
  As ocean acidification continues to impact marine ecosystems at unprecedented rates, phenotypic plasticity may allow organisms to withstand more stressful conditions. Genomic methods can elucidate molecular mechanisms that contribute to phenotypic plasticity, allowing for a deeper understanding of how physiological processes will be impacted by low pH. My dissertation examines the effects of ocean acidification on the Pacific oyster (*Crassostrea gigas*) stress response and reproduction; elucidate how exposure history impacts phenotype; and explore the role of functional role DNA methylation in somatic and reproductive tissue. I investigated the effect of regional environmental variation on the molecular physiology of *C. gigas* outplanted at five different estuarine sites (four in Puget Sound, one in Willapa Bay) in Washington, USA using gel-free proteomic methods. While there was no difference in survival, or any protein abundances due to pH differences between sites, *C. gigas* outplanted at the site with the highest temperature had significantly higher abundances of antioxidant enzymes and molecular chaperones, elucidating the molecular underpinnings of thermotolerance. In a hatchery setting, I explored the impact of ocean acidification on reproductive maturity and output. A seven week low pH exposure did not affect sex ratio or maturation stage; however, it did significantly affect survival of larvae. Even though adult oysters spent four months in ambient pH conditions between low pH exposure and strip spawning, larvae from females that experienced low pH conditions had significantly higher mortality. Finally, I conducted the first investigations examining the effect of ocean acidification in *C. gigas* methylomes. To investigate the role of environmentally-responsive methylation in reproductive tissue, I analyzed gonad methylomes of female *C. gigas* exposed to low pH. A total of 1,599 differentially methylated loci (DML) were found in gene bodies. The genic DML were associated with cilium movement, development, and cytoskeletal processes, implying a need to regulate cellular growth in the gonad in response to low pH. I then explored the influence of low pH on the somatic tissue methylome using diploid and triploid oyster ctenidia. Differences in ploidy status yielded 154 DML. These ploidy-DML were associated with cell-cell adhesion and dephosphorlylation processes, which are not commonly associated with methylome changes in organisms that undergo natural polyploidization. The 178 pH-DML were associated with processes commonly observed in oysters exposed to ocean acidification, including apoptosis, protein ubiquitination, zinc ion binding, and cytoskeletal processes. In both reproductive and somatic tissue, the enrichment of DML in genes with multiple transcripts could indicate a role for methylation to regulate gene expression via alternative splicing. Investigating the molecular underpinnings of responses to ocean acidification in *C. gigas* will provide a thorough understanding of this global aquaculture product’s ability to withstand future ocean conditions.
acknowledgments: |
  I am eternally grateful for the community that has supported me over the past five years. I cannot thank my adviser, Dr. Steven B. Roberts, enough for his mentorship. He gave me room to grow and think for myself as a scientist, while constantly supporting my goals and advocating for my best interests. He fostered a welcoming, community-oriented lab environment that I will deeply miss. My other committee members — Drs. Jacqueline Padilla-Gamiño, Jonathan P. Davis, Julian D. Olden, and Lauren Buckley — challenged me to think about my work broadly and were always enthusiastic about my work in a way that refreshed my own interests. Although they were not officially part of my committee, Drs. Hollie M. Putnam at the University of Rhode Island and Kathleen E. Lotterhos at Northeastern University taught me so much in our collaborations, and showed me how new faculty members could pursue engaging research while also advocating for better academic environments. 
  
  A big thank you to all past and present members of the Roberts Lab for helping me every time my code didn’t run, teaching me proper pipetting technique, and bringing levity and joy to what can feel like a slog-fest. The SAFS graduate student community has been integral to my time in Seattle; it was a joy to learn, protest, and laugh with you all.
  
  And most importantly, thank you to my family and my parents, Sudha Rajagopalan and Dr. Shankar Venkataraman. I would be nothing without you. Thank you, and I love you.

dedication: |
  To my Appa, Dr. Shankar Venkataraman. Your Appa reminded you not to forget to complete your Ph.D, so that you could do the same for me. 
  
  I completed it.
# End of UW thesis fields
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  huskydown::thesis_pdf: 
    latex_engine: xelatex
    extra_dependencies: ["flafter"]
#  huskydown::thesis_gitbook: default
#  huskydown::thesis_word: default
#  huskydown::thesis_epub: default
bibliography: bib/thesis.bib
link-citations: yes
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
# space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the huskydown package is
# installed and loaded. This huskydown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(huskydown))
  devtools::install_github("benmarwick/huskydown")
library(huskydown)
```

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters. -->

# Introduction {.unnumbered}

Pacific oysters (*Crassostrea gigas*; Thunberg 1793) are a commercially and ecologically relevant species, making them ideal models for studying physiological responses to ocean acidification. Research efforts have already identified consequences of ocean acidification for distinct life stages. Pacific oyster larvae experience developmental delays and reduced shell growth in response to experimental ocean acidification [@Gazeau2011; @Kurihara2007; @Timmins-Schiffman2013; @Waldbusser2014]. Key protein pathways are disrupted during metamorphosis [@Dineshram2016] and adulthood [@Timmins-Schiffman2014]. As seawater pCO<sub>2</sub> increases, adult *C. gigas* calcification rates decrease [@Gazeau2007], and their shells display significantly lower fracture toughness [@Timmins-Schiffman2014]. Exposure to experimental ocean acidification also negatively impacts growth, sperm motility, and egg viability in adult oysters [@Omoregie2019]. Although there is extensive research on ocean acidification’s impact on *C. gigas*, key uncertainties remain surrounding the mechanisms behind observed physiological responses. Knowing how the environment shapes physiological phenotypes on a mechanistic level could help identify potential pathways for future-proofing *C. gigas* aquaculture operations.

Genomics are the next frontier for understanding how environmental variability affects an organism’s physiological response and ability to acclimate to future ocean conditions. Epigenetic analysis can provide a direct link between changes in the environment and gene expression regulation. The epigenome consists of gene expression changes that do not arise from changes in the DNA sequence itself, with methylation of cytosine bases being the most studied mechanism [@Bird2002; @Deans2015]. Initial characterization of the *C. gigas* methylome has found that methylation occurs in a mosaic pattern and is concentrated in gene regions [@Gavery2013]. Environmental response genes that are less methylated are likely prone to more spurious transcription and alternative splicing patterns, thereby increasing phenotypic plasticity [@Roberts2012]. Recent studies have demonstrated that changes in the environment can affect DNA methylation patterns in other marine invertebrates [@Eirin-Lopez2018], so it is possible genomic regulation by DNA methylation may also be important for adaptation and acclimation in *C. gigas*. Additionally, manipulation of methylation patterns could be a method for “stress hardening” cultured species in hatchery settings [@Gavery2017]. Similarly, examination of the proteome — all the proteins in a sample — can shed light on physiological changes on a molecular level, since proteins direct all cellular functions [@Tomanek2014]. Since the proteome is dynamic, proteomic analysis can capture organismal response to real-time environmental conditions, similar to those experienced by *C. gigas* outplanted at aquaculture grow-out sites.

My dissertation uses *C. gigas* as a model system to examine molecular mechanisms important for ocean acidification response. I first explored the impacts of natural pH variation on the *C. gigas* proteome. Next, I investigated the effect of ocean acidification on oyster physiology in a controlled hatchery setting. Finally, I elucidated the mechanistic role of DNA methylation in responding to ocean acidification in somatic and reproductive tissues. My work provides a foundation for using molecular tools to promote resilient aquaculture in the face of climate stressors like ocean acidification.
